### ISSUE TITLE
user can't change timezone

### ISSUE THREAD

**Issue by noon92** [noon92/femtofox#7]
`femto@femtofox:~$ sudo timedatectl set-timezone UTC`
`Failed to set time zone: Access denied`

**Comment by Ruledo** [comment]
in chroot (noted in workflow doc):
rm /etc/localtime
ln -sf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime

Use these to lines anytime to change tz.

**Comment by noon92** [comment]
Fixed in usbconfig.sh

**Comment by noon92** [comment]
Reopened as reminder to fix usbconfig.sh - please take note @Ruledo.

Replace line 171 with ```      rm /etc/localtime
      ln -sf /usr/share/zoneinfo/$timezone /etc/localtime```
